### ISSUE TITLE
Rows missing after concat two dataframes

### ISSUE THREAD

**Issue by terrytangyuan** [blaze/dask#920] opened 2016-01-17 04:04 UTC
Several rows seem to be missing after `concat`, reproducible example: 
```
X = pd.DataFrame(dict(a=list('aabbcc')))
X = dd.from_pandas(X, npartitions=2)
y = pd.DataFrame(dict(labels=list('010011')))
y = dd.from_pandas(y, npartitions=2)
dd.multi.concat([X, y], axis=1).compute() # this should give 6 rows instead. 
```
Anything important to note that I missed?

**Comment by terrytangyuan** [comment] 2016-01-17 04:08
Oops this is not reproducible for some reason. I guess some caches from exisiting ipython environment affected this somehow. Feel free to close it but it may indicate some underlying issue?

**Comment by jcrist** [comment] 2016-01-17 04:08
What was the output in your example? I'm unable to reproduce:

```python
In [1]: import dask.dataframe as dd

In [2]: import pandas as pd

In [3]: X = pd.DataFrame(dict(a=list('aabbcc')))

In [4]: X = dd.from_pandas(X, npartitions=2)

In [5]: y = pd.DataFrame(dict(labels=list('010011')))

In [6]: y = dd.from_pandas(y, npartitions=2)

In [7]: dd.multi.concat([X, y], axis=1).compute()
Out[7]:
   a labels
0  a      0
1  a      1
2  b      0
3  b      0
4  c      1
5  c      1
```

**Comment by jcrist** [comment] 2016-01-17 04:11
> Feel free to close it but it may indicate some underlying issue? 

Without a reproducible example, I'd just be guessing at what you saw. I'll close this for now, feel free to reopen/make a new issue if it comes up again.

**Comment by terrytangyuan** [comment] 2016-01-17 04:12
Sure, thanks!

**Closed by jcrist** 2016-01-17 04:11 UTC
