### ISSUE TITLE
Error when reading a .bz2 file with dask 0.7.5

### ISSUE THREAD

**Issue by apiszcz** [blaze/dask#909] opened 2016-01-08 10:28 UTC
Read plain CSV works.
Read bz2 compressed version fails, assume the pandas read_csv capability is not fully supported.
Note I also tested with dtype definition, same error.

partial strack trace
        df = dd.read_csv(..., dtype={'my-column': float})

    Pandas has given us the following error when trying to parse the file:

      "utf-8"
   
==
Traceback
---------
  File "lib\dask\async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "lib\dask\async.py", line 245, in _execute_task
    return func(*args2)
  File "lib\dask\dataframe\io.py", line 69, in _read_csv
    raise ValueError(msg)

**Comment by jcrist** [comment] 2016-01-08 15:05
Looks like you have an encoding issue. A few things to try:

- We just released dask 0.7.6. Try upgrading, and see if that fixes your problem.
- Try passing in the encoding directly to the read_csv call (`encoding='utf-8'`). The default is your system encoding, which might not be "utf-8".

**Comment by apiszcz** [comment] 2016-01-08 15:08
Will do, however I'm seeing other odd behavior after I 'load' the data.
df.head() runs 'for a very long time' never returns a value, 6 million rows
4 columns.

**Comment by jcrist** [comment] 2016-01-08 15:19
Yeah, that's probably due to how we're parsing the files. I'm unable to reproduce using a `bz2`, non ascii encoded csv that I quickly made. If you can create a small, reproducible test case (if your data isn't sharable, a small bz2 file of fake data that exhibits the same problem would also work) for us that would greatly help in debugging this.

The file encoding might also not be `'utf-8'` - pandas is just throwing a `ValueError('utf-8')`, which is less than informative. If you're comfortable mucking in source code, we could modify the line where dask swallows the traceback, which would help in debugging.

**Comment by apiszcz** [comment] 2016-01-08 15:22
I can share a sample if i can get your email address.​

**Comment by apiszcz** [comment] 2016-01-08 15:26
Note: I'm using Python 3.5.1.

**Comment by jcrist** [comment] 2016-01-08 15:30
> I can share a sample if i can get your email address.​
jcrist at continuum dot io

**Comment by mrocklin** [comment] 2016-01-08 15:36
Note that there is also a [pretty serious performance flaw](https://github.com/blaze/dask/issues/901) with `dask.dataframe.read_csv` and compressed files.  If you have the space it's worthwhile to unzip ahead of time (also because bz2 decompression is very very slow, and something you only want to do once.)

**Comment by apiszcz** [comment] 2016-01-08 15:39
Understand, I am testing, bz2 is a hit, compressed file system files on
windows seem optimal.

**Comment by jcrist** [comment] 2016-01-08 17:03
@apiszcz , thanks for the bug report. We weren't properly determining the compression based off the file extension. This should be fixed by #910.

**Comment by mrocklin** [comment] 2016-01-08 17:04
Ah, I didn't notice that.  Question though, does this deviate with Pandas behavior?

**Comment by jcrist** [comment] 2016-01-08 17:05
No, `compression='infer'` by default in pandas `read_csv` as well. This was never tested, as all tests specified compression directly.

**Comment by mrocklin** [comment] 2016-01-08 17:05
Ah, that might be new

**Comment by jcrist** [comment] 2016-01-08 17:08
Looks like it was added in 0.16.1: http://pandas.pydata.org/pandas-docs/version/0.17.0/whatsnew.html#whatsnew-0161-api.

**Comment by apiszcz** [comment] 2016-01-08 17:12
ack, infer is recent, i'm using 17.1
Jim if you have time and get normal behavior when you do df.head() I'd
appreciate knowing that.

**Comment by jcrist** [comment] 2016-01-08 17:14
Yep, works fine for me. Only argument to `read_csv` was the bz2 filename.

**Closed** 2016-01-12 05:57 UTC
