### ISSUE TITLE
Can't visualize graphs as PNG

### ISSUE THREAD

**Issue by Carreau** [blaze/dask#788] opened 2015-10-16 23:40 UTC
Seen with @mrocklin today in person.

```
$ python3
Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.array as da
>>> x = da.ones(shape=(5,5), chunks=3)
>>> x.visualize()
Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pic plain plain-ext pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4
<IPython.core.display.Image object> # does not render on notebook, actually no data.
```

Works if force format as svg, graphviz CLI (2.38) installed with conda, graphviz lib (0.4.7) installed with pip. Dask master as of today.  

Error message appear launching terminal if executed in notebook.
SVG works fine. Conda have libpng installed.

**Comment by jcrist** [comment] 2015-10-17 00:04
I cannot reproduce. It may be an issue with the graphviz cli installed from conda. The python wrapper (and our use of it) is just a thin layer above that. To test, create a file "test.dot", with this in it:

```dot
digraph graphname {
     a -> b -> c;
     b -> d;
 }
```

And then run

```
dot test.dot -Tpng -o test.png
```

**Comment by Carreau** [comment] 2015-10-17 00:08
Yep fails too. Did you know who to ping at Continuum to investigate that. 
I just removed and reinstall graphviz and it does not fix the problem. 

(Note dask does not seem to depends on graphviz, should it ?)

**Comment by jcrist** [comment] 2015-10-17 00:14
I'm forwarding this upstream to them. What OS are you on?

> (Note dask does not seem to depends on graphviz, should it ?) 

In general, we try to only depend on the mandatory packages - visualizing graphs not being one of them. Note that most linux distributions/osx have graphviz available through the system package manager (I installed with homebrew).

**Comment by jcrist** [comment] 2015-10-17 00:21
Actually, you should just file an issue here: https://github.com/ContinuumIO/anaconda-recipes. I'm going to close this, as the problem is upstream. I'll ping them as well, so hopefully we can get this resolved.

**Closed by jcrist** 2015-10-17 00:21 UTC

**Comment by shoyer** [comment] 2015-10-17 02:50
I've had issues when using Legacy Python with conda's graphviz on OS X, but Python 3 works fine. Go figure.

**Comment by msarahan** [comment] 2015-10-17 03:16
I think this might be an issue with the build recipe for graphviz not enabling png at compile time.  The correct place to report issues like this is currently at https://github.com/ContinuumIO/anaconda-issues, and the anaconda team will triage from there.

**Comment by Carreau** [comment] 2015-10-20 18:22
Thanks, sorry for the delay, will update-retry and report there, if still the case.
