### ISSUE TITLE
associative operations max,mean run out of memory when it could be avoided

### ISSUE THREAD

**Issue by 22csnyder** [blaze/dask#883] opened 2015-12-17 09:09 UTC
Scenario:
I have an array Array with 
shape: (465,15,500,2100)
chunks: ( 465*(1,), 15*(1,), (500,), (2100) )
physical interpretation: Time, Z, Y, X

(1)Simple example. I would like to calculate the maximum value (Z,Y,X) can take over all T.
max_Array=da.max( Array , axis=0 )
This runs into a memory error. It "shouldn't" because there is a way for it to work. Instead of loading every frame, for special operations (add,max,matrix multiply), you can just load a few frames at a time and keep the intermediate results, keeping a "max_so_far" type variable for each Z,Y,X position.

(2) I couldn't find a workaround because actually I want a maximum value of a moving average, and each individual moving average calculation can't fit in memory!. I want to average each (15,500,2100) matrix with its 30 closest neighbors in T.
i.e.
box_average=da.stack( [ da.mean( Array[t-15:t+15] , axis=0) for t in range(len(Array))] , axis=0)  

When I run this I find that not even a single frame fits in memory. i.e. the following workaround fails:
Result = [ box_average[t].compute() for each t]

(3) Piling on difficulty, I have some interest in taking a median(!) operator instead of a max. I noticed this was absent from the operations in dask.array. Not a big deal. This is of course difficult to compute out of core because you have to be able to load at least half of the data into memory at once.

Best,
Chris Snyder

**Comment by mrocklin** [comment] 2015-12-17 14:52
1.  Your timing is actually really good here.  @jcrist recently added [tree reductions](https://github.com/blaze/dask/pull/839).  If you're on master you can use the keyword argument `split_every=` to manage the granularity of the intermediate reductions.  

    @jcrist this is another argument for lowering the size of the default value for `split_every=`.  One of @22csnyder 's slices is 126 MB.  I still think that a default value of about 8 is right here.  

    @22csnyder you can also set this value globally if that's easier
    
        dask.set_options(split_every=8)

2.  Hopefully the solution to 1 makes 2 more possible.  It'll be an interesting problem though and I'm not sure what's likely to happen.  Hopefully the scheduler can find its way through that computation.  If it can't then it'll be a fun use case to motivate scheduler improvements (which are good for everyone)

3.  I have no idea how to compute the median in low space.  We could improve our quantile computations if you're comfortable with an approximation.

**Comment by 22csnyder** [comment] 2015-12-17 15:19
Ah I see. No, I'm on the pip distributed version. I made an ugly workaround, checked back an hour later and stored the result. So, I'm good for a little while, but I want to come back to this.

Q1) So, is "split_every" intelligently chosen, or does my program viability depend on choosing the right number? Also, let me just wildly oversimplify something I don't understand: "Can't you just keep loading chunks until you hit a memory error, then use that number as the split_every_n_chunks?"

Q3) Don't worry about the median thing. Although, that's a *really* interesting algorithm problem now that I think about it.

**Comment by mrocklin** [comment] 2015-12-17 15:23
1.  `split_every` is not intelligently chosen (although that would be a great contribution if you're interested :)).  Currently it defaults to the number 32.  Like `chunks=` it's left to the wisdom of the user.

**Comment by mrocklin** [comment] 2016-01-05 18:52
Is this resolved with tree reductions?

**Comment by 22csnyder** [comment] 2016-01-05 20:34
Sorry Matthew,

I still haven't tried it. My work just hasn't taken me back to the point
where it's something I need to do again.

Best,
Chris S

**Comment by shoyer** [comment] 2016-01-05 22:29
Looking at this again, why not even pick a default of `split_every=1`? That would seem much better for streaming data. Does it actually cause an appreciable slow-down to create so many tasks?

**Comment by jcrist** [comment] 2016-01-05 22:33
> Looking at this again, why not even pick a default of split_every=1?

`split_every=1` doesn't make sense, because it defines the maximum number of nodes to be brought together in the reduction. With only 1 chunk, there's nothing to combine. Because of this, it's thresholded at 2: https://github.com/blaze/dask/blob/master/dask/array/reductions.py#L41.

**Comment by mrocklin** [comment] 2016-01-05 22:34
How about for `split_every=2` then?

**Comment by mrocklin** [comment] 2016-01-05 22:40
I'm in favor of lowering the default considerably.  In worst case `split_every=2` doubles the scheduling overhead.  This can be significant in bad cases.  I'm generally in favor of 4 or 8.

**Comment by shoyer** [comment] 2016-01-05 22:40
> split_every=1 doesn't make sense, because it defines the maximum number of nodes to be brought together in the reduction

Oops :). Yes, I meant `split_every=2`.

My only concern here is whether the dask scheduler is smart enough to properly prioritize tasks to minimize memory usage even in deep trees. A "reduce-like" graph (e.g., as produced by `reduce(operator.add, list_of_dask_arrays)`) seems like it might be easier to optimize because it's always obvious which task should be computed next.

**Comment by mrocklin** [comment] 2016-01-05 22:42
It would be cool to be able to visualize these traces more effectively.  My money is on the dask scheduler handling these just fine.  If it can't then we can probably find a way to make it better.

**Comment by jcrist** [comment] 2016-01-05 22:47
Pathological case:

```
In [30]: a = da.random.normal(size=(1e6, 10), chunks=(500, 10))

In [31]: x = a.sum(split_every=32)

In [32]: len(x.dask)
Out[32]: 4501

In [33]: %time x.compute()
CPU times: user 1.36 s, sys: 388 ms, total: 1.75 s
Wall time: 1.13 s
Out[33]: 4258.8755234052878

In [34]: x = a.sum(split_every=2)

In [35]: len(x.dask)
Out[35]: 6001

In [36]: %time x.compute()
CPU times: user 1.84 s, sys: 547 ms, total: 2.39 s
Wall time: 1.67 s
Out[36]: 4258.8755234052869

In [37]: (1.67 - 1.13)/1.13
Out[37]: 0.47787610619469034
```

Because each task is relatively cheap, this is only measuring the overhead in the scheduler. With more expensive `combine` functions (most of these are cheap though), this would be larger. So a number of 4 or 8 might make sense.

**Comment by mrocklin** [comment] 2016-01-05 22:48
Even in this pathological case the outcome really isn't all that bad.

**Comment by mrocklin** [comment] 2016-01-22 16:05
I'm assuming that `split_every` resolves this problem.  Closing.  Feel free to reopen of the issue is still live.

**Closed by mrocklin** 2016-01-22 16:05 UTC
