### ISSUE TITLE
test_bag.test_map_function_w_multi_args hangs.

### ISSUE THREAD

**Issue by cowlicks** [blaze/dask#206] opened 2015-05-13 20:54 UTC
When testing with binstar build on windows the function `test_bag.test_map_function_with_multiple_arguments` hangs. See example here:

https://binstar.org/blaze/dask/builds/41/12#L2153

**Comment by mrocklin** [comment] 2015-05-13 20:57
I'm working through dask issues on windows now.  Was side tracked a little by xdata things.  If you're blocking on this then I suggest switching to another thread for an hour or two.

**Comment by cowlicks** [comment] 2015-05-13 21:01
Nope, just wanted to document it.

**Comment by mrocklin** [comment] 2015-05-14 14:44
I'm unable to reproduce this on my local machine.  From the looks of it it seems like dill is misbehaving; this is also the issue on [linux-32](https://binstar.org/blaze/dask/builds/45/2).  

@mmckerns is there a reason why dill might misbehave within a test file?  Lambdas and partials don't seem to serialize well on windows or 32 bit linux (though they're fine on other platforms.)

**Comment by mmckerns** [comment] 2015-05-16 15:06
@mrocklin: I'd need to know how you are using the test file.  So, you mean that it's an *uninstalled* file?   I know there's some potential for `dill` getting confused depending on how the file is run. If a file gets run as `__main__` for the dump, and through an import for the load… there can be an issue, as certain objects use the name of the module instead of serializing the source.  If this issue is unrelated to your recent (`dill`) tickets, I'll need more context on what you are seeing.

**Comment by mrocklin** [comment] 2015-05-16 15:14
I'm shamefully ignorant of packaging best practices.  I suspect that we're not shipping test files appropriately so yes, your guess is probably correct.

More generally though, in what context would we want to trust `__main__`?  Here is another minimal failing example.

### Process 1

```python
In [1]: from math import sin

In [2]: def sync(x):
    return sin(x) / x
   ...: 

In [3]: import dill

In [4]: dill.dumps(sync)
Out[4]: '\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_unmarshal\nq\x01U\x83c\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00s\x0e\x00\x00\x00t\x00\x00|\x00\x00\x83\x01\x00|\x00\x00\x15S(\x01\x00\x00\x00N(\x01\x00\x00\x00t\x03\x00\x00\x00sin(\x01\x00\x00\x00t\x01\x00\x00\x00x(\x00\x00\x00\x00(\x00\x00\x00\x00s\x1e\x00\x00\x00<ipython-input-2-96199cb1004b>t\x04\x00\x00\x00sync\x01\x00\x00\x00s\x02\x00\x00\x00\x00\x01q\x02\x85q\x03Rq\x04c__builtin__\n__main__\nU\x04syncq\x05NN}q\x06tq\x07Rq\x08.'
```

### Process 2

```python
In [1]: import dill

In [2]: f = dill.loads('\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_unmarshal\nq\x01U\x83c\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00s\x0e\x00\x00\x00t\x00\x00|\x00\x00\x83\x01\x00|\x00\x00\x15S(\x01\x00\x00\x00N(\x01\x00\x00\x00t\x03\x00\x00\x00sin(\x01\x00\x00\x00t\x01\x00\x00\x00x(\x00\x00\x00\x00(\x00\x00\x00\x00s\x1e\x00\x00\x00<ipython-input-2-96199cb1004b>t\x04\x00\x00\x00sync\x01\x00\x00\x00s\x02\x00\x00\x00\x00\x01q\x02\x85q\x03Rq\x04c__builtin__\n__main__\nU\x04syncq\x05NN}q\x06tq\x07Rq\x08.')

In [3]: f(1)
NameError: global name 'sin' is not defined
```

**Comment by mmckerns** [comment] 2015-05-16 15:49
I'm going to refer you to this: https://github.com/uqfoundation/dill/pull/86, which I assume you have already seen, as I've just pointed it out to you on other tickets.  I think it's all the same issue, and one that `dill` has a robust general solution to… but it's currently in an uncommitted edit to the referenced PR.  It will get committed as soon as I get the time to do a few last tweaks to it to make sure I don't apply it stupidly.

**Comment by mrocklin** [comment] 2015-05-17 14:52
The code in that PR does indeed resolve the examples that I've created so far.

**Comment by mmckerns** [comment] 2015-05-17 21:48
That's what I thought.  So, the issue is that the PR creates other holes… so I have split the PR into two separate functions, and need to apply them intelligently to get all the cases correct (and not squash anything).

**Comment by mrocklin** [comment] 2015-09-04 15:20
This no longer seems to be an issue.

**Closed by mrocklin** 2015-09-04 15:20 UTC
Labels: serialization
